resources:
  repositories:
    - repository: templates
      type: git
      name: SRE/HIAE.SRE.Templates
      ref: refs/heads/master
stages:
  - template: catalog/openshift-react-v4.yml@templates
    parameters:
      node version: "18.0.0"
trigger:
  - develop
  - hotfix